[en]
  weight = 1
  # language code
  languageCode = "fr"
  # language name
  languageName = "Français"
  # whether to include Chinese/Japanese/Korean
  hasCJKLanguage = false
  # default amount of posts in each pages
  paginate = 12
  # [UA-XXXXXXXX-X] google analytics code (replaced by params.analytics.google)
  googleAnalytics = ""
  # copyright description used only for seo schema
  copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
  # Menu config
  [menu]
    [[menu.main]]
      identifier = "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      name = "Posts"
      url = "/posts/"
      # title will be shown when you hover on this menu link.
      title = ""
      weight = 1
    [[menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 2
    [[menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "Categories"
      url = "/categories/"
      title = ""
      weight = 3
# TODO
#    [[menu.main]]
#      identifier = "series"
#      pre = ""
#      post = ""
#      name = "Series"
#      url = "/series/"
#      title = ""
#      weight = 4
    [[menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "A propos"
      url = "/posts/à-propos/"
      title = ""
      weight = 5
  [params]
    # site description
    description = ""
    # site keywords
    keywords = ["Theme", "Hugo"]
    # App icon config
    [en.params.app]
      # optional site title override for the app when added to an iOS home screen or Android launcher
      title = "DoIt"
      # whether to omit favicon resource links
      noFavicon = false
      # modern SVG favicon to use in place of older style .png and .ico files
      svgFavicon = ""
      # Safari mask icon color
      iconColor = "#5bbad5"
      # Windows v8-10 tile color
      tileColor = "#da532c"
    # Search config
    [params.search]
      enable = true
      # type of search engine ("lunr", "algolia", "fuse")
      type = "algolia"
      # max index length of the chunked content
      contentLength = 4000
      # placeholder of the search bar
      placeholder = ""
      # max number of results length
      maxResultLength = 10
      # snippet length of the result
      snippetLength = 300
      # HTML tag name of the highlight part in results
      highlightTag = "em"
      # whether to use the absolute URL based on the baseURL in search index
      absoluteURL = false
      [params.search.algolia]
        index = "en_index"
        appID = "5YGRNRQK1G"
        searchKey = "0ff6874805de24b84aa1d5ebccad56cd"
      [params.search.fuse]
        # https://fusejs.io/api/options.html
        isCaseSensitive = false
        minMatchCharLength = 2
        findAllMatches = false
        location = 0
        threshold = 0.1
        distance = 100
        ignoreLocation = true
        useExtendedSearch = false
        ignoreFieldNorm = false
    # Home page config
    [params.home]
      # amount of RSS pages
      rss = 10
      # Home page profile
      [params.home.profile]
        enable = true
        # Gravatar Email for preferred avatar in home page
        gravatarEmail = ""
        # URL of avatar shown in home page
        avatarURL = "/images/avatar.webp"
        # title shown in home page (HTML format is supported)
        title = ""
        # subtitle shown in home page
        subtitle = "A Clean, Elegant but Advanced Hugo Theme"
        # whether to use typeit animation for subtitle
        typeit = true
        # whether to show social links
        social = true
        # disclaimer (HTML format is supported)
        disclaimer = ""
      # Home page posts
      [params.home.posts]
        enable = true
        # special amount of posts in each home posts page
        paginate = 7
    # Social config in home page
    [params.social]
      GitHub = ""
      Linkedin = ""
      Twitter = ""
      Instagram = ""
      Facebook = ""
      Telegram = ""
      Medium = ""
      Gitlab = ""
      Youtubelegacy = ""
      Youtubecustom = ""
      Youtubechannel = ""
      Tumblr = ""
      Quora = ""
      Keybase = ""
      Pinterest = ""
      Reddit = ""
      Codepen = ""
      FreeCodeCamp = ""
      Bitbucket = ""
      Stackoverflow = ""
      Weibo = ""
      Odnoklassniki = ""
      VK = ""
      Flickr = ""
      Xing = ""
      Snapchat = ""
      Soundcloud = ""
      Spotify = ""
      Bandcamp = ""
      Paypal = ""
      Fivehundredpx = ""
      Mix = ""
      Goodreads = ""
      Lastfm = ""
      Foursquare = ""
      Hackernews = ""
      Kickstarter = ""
      Patreon = ""
      Steam = ""
      Twitch = ""
      Strava = ""
      Skype = ""
      Whatsapp = ""
      Zhihu = ""
      Douban = ""
      Angellist = ""
      Slidershare = ""
      Jsfiddle = ""
      Deviantart = ""
      Behance = ""
      Dribbble = ""
      Wordpress = ""
      Vine = ""
      Googlescholar = ""
      Researchgate = ""
      Thingiverse = ""
      Devto = ""
      Gitea = ""
      XMPP = ""
      Matrix = ""
      Bilibili = ""
      ORCID = ""
      QQ = ""
      QQGroup = ""
      Liberapay = ""
      Ko-Fi = ""
      BuyMeACoffee = ""
      Linktree = ""
      Email = ""
      RSS = true
      [params.social.Mastodon]
        id = "@xxxx"
        prefix = "https://mastodon.technology/"
      [params.social.Diaspora]
        id = "@xxxx"
        prefix = "https://yyyy/"
    # Sponsor config
    [params.sponsor]
      enable = false
      bio = "If you find this post helpful, please consider sponsoring."
      link = "https://github.com/sponsors/HEIGE-PCloud"
      # custom = "<a href=\"https://www.buymeacoffee.com/PCloud\" target=\"_blank\"><img src=\"https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png\" alt=\"Buy Me A Coffee\" style=\"height: 40px !important;width: 145 !important;\" ></a>"